version: '3'

services:

    #nginx web app
    # server:
    #     build: 
    #         context : ./docker/server/
    #         dockerfile: Dockerfile
    #         args: 
    #           NAME_SERVER: remote-test.vicoders.com
    #           HOST_NAME: 172.20.0.5
    #           PORT: 3000

    #     image: server:0.1
    #     container_name: server
    #     networks:
    #         vmms_network:
    #             ipv4_address: 172.20.0.4
    #     ports:
    #         - '80:80'
    #         - '443:443'
    #     volumes:
    #         # - ./etc/nginx/conf.d:/etc/nginx/conf.d
    #         - ./var/www/certbot:/var/www/certbot
    #         - ./etc/nginx/letsencrypt/:/etc/letsencrypt/
    #     restart: always

    nodejs:
      build:
          context : ./docker/nodejs/
          dockerfile: Dockerfile
          args:
            NAME_SERVER: nodejs.vicoders.com
            MYSQL_USER: remote
            MYSQL_PASS: Vmms123456@s
            MYSQL_HOST: 172.20.0.3

      networks:
          vmms_network:
            ipv4_address: 172.20.0.5
      ports: 
        - '3000:3000'
      volumes:
        - ./source_code:/var/www/web/

      depends_on:
        - mysql


    #MySQL config
    mysql:
        #build: ./docker/mysql
        image: 'bitnami/mysql:latest'
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: Quenanhdi123s
            MYSQL_USER: remote
            MYSQL_PASSWORD: Vmms123456@s
            MYSQL_DATABASE: vicoders_db
            MYSQL_ROOT_HOST: 0.0.0.0 
       
        networks:
            vmms_network:
                ipv4_address: 172.20.0.3
        ports:
            - '3306:3306'
        volumes:
            - ./var/lib/mysql:/bitnami
            - ./etc/bitnami/mysql/conf:/opt/bitnami/mysql/conf
        restart: always

networks:
  vmms_network:
 
    ipam:
       config:
           - subnet: 172.20.0.0/16
